name: Setup Dependencies
description: Sets up Node.js, cache and installs dependencies
inputs:
  GITHUB_TOKEN:
    description: GitHub token to set up remote caching
    required: true
  TURBO_SERVER_TOKEN:
    description: Turborepo token
    required: true
runs:
  using: "composite"
  steps:
    - name: Turborepo Caching Server
      uses: felixmosh/turborepo-gh-artifacts@v3
      with:
        repo-token: ${{ inputs.GITHUB_TOKEN }}
        server-token: ${{ inputs.TURBO_SERVER_TOKEN }}
    - uses: oven-sh/setup-bun@v2
      name: Install Bun
    - uses: actions/cache@v4
      name: Setup cache
      with:
        path: |
          ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
    - name: Install dependencies
      shell: bash
      run: bun i
