import "@total-typescript/ts-reset"
import "./i18n/"
import type {} from "graphql-request"
import type {} from "swr"
export { useAppStore } from "./common/store/app"
export { usePendingTransactionStore } from "@palladxyz/vault"
export { Router } from "./router"
export { WebConnectorRoute } from "./web-connector/routes/web-connector"
export * as Icons from "lucide-react"
import "./globals.css"
