query Transactions($address: String!) {
  transactions(query: { from: $address, OR: { to: $address } }) {
    amount
    to
    token
    kind
    isDelegation
    hash
    from
    fee
    failureReason
    dateTime
    blockHeight
  }
}
