query Transaction($hash: String!) {
  transaction(query: { hash: $hash }) {
    amount
    blockHeight
    dateTime
    failureReason
    fee
    from
    hash
    isDelegation
    kind
    to
    token
  }
}
