import { Inter } from 'next/font/google'

import { LandingLayout } from '@/app/LandingLayout'

const inter = Inter({ subsets: ['latin'] })

import './reset.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LandingLayout>{children}</LandingLayout>
      </body>
    </html>
  )
}
