name: Extension E2E
on:
  workflow_run:
    workflows: ["Extension CI"]
    branches: [main]
    types: [completed]
  workflow_dispatch:
jobs:
  e2e:
    name: Run E2E tests
    env:
      VITE_APP_E2E: true
      VITE_APP_DEFAULT_NETWORK_ID: mina:devnet
      NODE_OPTIONS: "--max_old_space_size=4096"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup env
        uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TURBO_SERVER_TOKEN: ${{ secrets.TURBO_SERVER_TOKEN }}
      - name: Build extension
        env:
          TURBO_API: "http://127.0.0.1:9080"
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: pallad
        run: VITE_APP_E2E=$VITE_APP_E2E VITE_APP_DEFAULT_NETWORK_ID=$VITE_APP_DEFAULT_NETWORK_ID pnpm build:extension
      - name: Install Chromium for Playwright
        working-directory: apps/extension
        run: pnpm test:e2e:install
      - name: Run E2E tests
        run: pnpm test:e2e:extension
      - uses: actions/upload-artifact@v4
        with:
          name: pallad-extension-e2e
          path: apps/extension/playwright-report/
